{ ... }:
{
  programs.tint2 = {
    enable = true;
    extraConfig = # ini
      ''
        #---- Generated by tint2conf aa1e ----
        # See https://gitlab.com/o9000/tint2/wikis/Configure for
        # full documentation of the configuration options.
        #-------------------------------------
        # Gradients
        #-------------------------------------
        # Backgrounds
        # Background 1: Panel
        rounded = 0
        border_width = 0
        border_sides = TBLR
        border_content_tint_weight = 0
        background_content_tint_weight = 0
        background_color = #000000 60
        border_color = #000000 30
        background_color_hover = #000000 60
        border_color_hover = #000000 30
        background_color_pressed = #000000 60
        border_color_pressed = #000000 30

        # Background 2: Default task, Iconified task
        rounded = 4
        border_width = 1
        border_sides = TBLR
        border_content_tint_weight = 0
        background_content_tint_weight = 0
        background_color = #777777 20
        border_color = #777777 30
        background_color_hover = #aaaaaa 22
        border_color_hover = #eaeaea 44
        background_color_pressed = #555555 4
        border_color_pressed = #eaeaea 44

        # Background 3: Active task
        rounded = 4
        border_width = 1
        border_sides = TBLR
        border_content_tint_weight = 0
        background_content_tint_weight = 0
        background_color = #777777 20
        border_color = #ffffff 40
        background_color_hover = #aaaaaa 22
        border_color_hover = #eaeaea 44
        background_color_pressed = #555555 4
        border_color_pressed = #eaeaea 44

        # Background 4: Urgent task
        rounded = 4
        border_width = 1
        border_sides = TBLR
        border_content_tint_weight = 0
        background_content_tint_weight = 0
        background_color = #aa4400 100
        border_color = #aa7733 100
        background_color_hover = #cc7700 100
        border_color_hover = #aa7733 100
        background_color_pressed = #555555 4
        border_color_pressed = #aa7733 100

        # Background 5: Tooltip
        rounded = 1
        border_width = 1
        border_sides = TBLR
        border_content_tint_weight = 0
        background_content_tint_weight = 0
        background_color = #222222 100
        border_color = #333333 100
        background_color_hover = #ffffaa 100
        border_color_hover = #000000 100
        background_color_pressed = #ffffaa 100
        border_color_pressed = #000000 100

        #-------------------------------------
        # Panel
        panel_items = TSC
        panel_size = 100% 30
        panel_margin = 0 0
        panel_padding = 2 0 2
        panel_background_id = 1
        wm_menu = 1
        panel_dock = 0
        panel_pivot_struts = 0
        panel_position = top center horizontal
        panel_layer = top
        panel_monitor = all
        panel_shrink = 0
        autohide = 0
        autohide_show_timeout = 0
        autohide_hide_timeout = 0.5
        autohide_height = 1
        strut_policy = follow_size
        panel_window_name = tint2
        disable_transparency = 1
        mouse_effects = 1
        font_shadow = 0
        mouse_hover_icon_asb = 100 0 10
        mouse_pressed_icon_asb = 100 0 0
        scale_relative_to_dpi = 0
        scale_relative_to_screen_height = 0

        #-------------------------------------
        # Taskbar
        taskbar_mode = single_desktop
        taskbar_hide_if_empty = 0
        taskbar_padding = 0 0 2
        taskbar_background_id = 0
        taskbar_active_background_id = 0
        taskbar_name = 1
        taskbar_hide_inactive_tasks = 0
        taskbar_hide_different_monitor = 0
        taskbar_hide_different_desktop = 0
        taskbar_always_show_all_desktop_tasks = 0
        taskbar_name_padding = 4 2
        taskbar_name_background_id = 0
        taskbar_name_active_background_id = 0
        taskbar_name_font_color = #e3e3e3 100
        taskbar_name_active_font_color = #ffffff 100
        taskbar_distribute_size = 0
        taskbar_sort_order = none
        task_align = left

        #-------------------------------------
        # Task
        task_text = 1
        task_icon = 1
        task_centered = 1
        urgent_nb_of_blink = 100000
        task_maximum_size = 150 35
        task_padding = 2 2 4
        task_tooltip = 1
        task_thumbnail = 0
        task_thumbnail_size = 210
        task_font_color = #ffffff 100
        task_background_id = 2
        task_active_background_id = 3
        task_urgent_background_id = 4
        task_iconified_background_id = 2
        mouse_left = toggle_iconify
        mouse_middle = none
        mouse_right = close
        mouse_scroll_up = toggle
        mouse_scroll_down = iconify

        #-------------------------------------
        # System tray (notification area)
        systray_padding = 0 4 2
        systray_background_id = 0
        systray_sort = ascending
        systray_icon_size = 24
        systray_icon_asb = 100 0 0
        systray_monitor = 1
        systray_name_filter =

        #-------------------------------------
        # Launcher
        launcher_padding = 2 4 2
        launcher_background_id = 0
        launcher_icon_background_id = 0
        launcher_icon_size = 24
        launcher_icon_asb = 100 0 0
        launcher_icon_theme_override = 0
        startup_notifications = 1
        launcher_tooltip = 1

        #-------------------------------------
        # Clock
        time1_format = %H:%M
        time2_format = %A %d %B
        time1_timezone =
        time2_timezone =
        clock_font_color = #ffffff 100
        clock_padding = 2 0
        clock_background_id = 0
        clock_tooltip =
        clock_tooltip_timezone =
        clock_lclick_command =
        clock_rclick_command = orage
        clock_mclick_command =
        clock_uwheel_command =
        clock_dwheel_command =

        #-------------------------------------
        # Battery
        battery_tooltip = 1
        battery_low_status = 10
        battery_low_cmd = xmessage 'tint2: Battery low!'
        battery_full_cmd =
        battery_font_color = #ffffff 100
        bat1_format =
        bat2_format =
        battery_padding = 1 0
        battery_background_id = 0
        battery_hide = 101
        battery_lclick_command =
        battery_rclick_command =
        battery_mclick_command =
        battery_uwheel_command =
        battery_dwheel_command =
        ac_connected_cmd =
        ac_disconnected_cmd =

        #-------------------------------------
        # Tooltip
        tooltip_show_timeout = 0.5
        tooltip_hide_timeout = 0.1
        tooltip_padding = 4 4
        tooltip_background_id = 5
        tooltip_font_color = #dddddd 100
      '';
  };

  # rc.xml: Openbox's own compiled-in mouse defaults (see
  # bind_default_mouse() in openbox/config.c), restated because
  # supplying a <mouse> section at all wipes every default
  # binding rather than overriding individual ones. Two changes
  # from stock: Frame drag moves from Alt+Left/Alt+Middle to
  # Super+Left/Super+Middle, so Alt+click/drag reaches clients
  # (Reaper) untouched; and a Root context is added (absent from
  # the compiled-in defaults) so right-click on the desktop still
  # opens the root menu, per menu.xml below. Everything else
  # (keyboard, theme, focus, desktops, ...) is left at Openbox's
  # defaults.
  xdg.configFile."openbox/rc.xml".text = ''
    <?xml version="1.0" encoding="UTF-8"?>
    <openbox_config xmlns="http://openbox.org/3.4/rc">
      <mouse>
        <context name="Client Desktop">
          <mousebind button="Left Middle Right" action="Press">
            <action name="Focus"/>
          </mousebind>
        </context>

        <context name="Titlebar Bottom BLCorner BRCorner TLCorner TRCorner Close Maximize Iconify Icon AllDesktops Shade">
          <mousebind button="Left" action="Press">
            <action name="Focus"/>
          </mousebind>
        </context>

        <context name="Client Titlebar BLCorner BRCorner TLCorner TRCorner Close Maximize Iconify Icon AllDesktops Shade">
          <mousebind button="Left" action="Click">
            <action name="Raise"/>
          </mousebind>
        </context>

        <context name="Titlebar">
          <mousebind button="Middle" action="Click">
            <action name="Lower"/>
          </mousebind>
          <mousebind button="Left" action="Drag">
            <action name="Move"/>
          </mousebind>
        </context>

        <context name="Close">
          <mousebind button="Left" action="Click">
            <action name="Close"/>
          </mousebind>
        </context>

        <context name="Maximize">
          <mousebind button="Left" action="Click">
            <action name="ToggleMaximize"/>
          </mousebind>
        </context>

        <context name="Iconify">
          <mousebind button="Left" action="Click">
            <action name="Iconify"/>
          </mousebind>
        </context>

        <context name="AllDesktops">
          <mousebind button="Left" action="Click">
            <action name="ToggleOmnipresent"/>
          </mousebind>
        </context>

        <context name="Shade">
          <mousebind button="Left" action="Click">
            <action name="ToggleShade"/>
          </mousebind>
        </context>

        <context name="TLCorner TRCorner BLCorner BRCorner Top Bottom Left Right">
          <mousebind button="Left" action="Drag">
            <action name="Resize"/>
          </mousebind>
        </context>

        <context name="Frame">
          <mousebind button="W-Left" action="Drag">
            <action name="Move"/>
          </mousebind>
          <mousebind button="W-Middle" action="Drag">
            <action name="Resize"/>
          </mousebind>
        </context>

        <context name="Root">
          <mousebind button="Right" action="Press">
            <action name="ShowMenu"><menu>root-menu</menu></action>
          </mousebind>
          <mousebind button="Middle" action="Press">
            <action name="ShowMenu"><menu>client-list-combined-menu</menu></action>
          </mousebind>
        </context>
      </mouse>
    </openbox_config>
  '';

  # jgmenu (github.com/jgmenu/jgmenu) replaces obmenu-generator:
  # right-click on the desktop still opens this static Openbox
  # pipe-menu (unchanged rc.xml/mousebind), but its one entry now
  # just launches jgmenu's own self-drawn app menu instead of
  # piping obmenu-generator-generated XML into Openbox's menu
  # renderer. jgmenu builds its XDG application list itself
  # (csv_cmd defaults to "apps"), so no separate desktop-file-path
  # config is needed the way obmenu-generator required.
  xdg.configFile."openbox/menu.xml".text = ''
    <?xml version="1.0" encoding="utf-8"?>
    <openbox_menu>
        <menu id="root-menu" label="OpenBox 3">
            <item label="Applications">
                <action name="Execute">
                    <command>jgmenu_run</command>
                </action>
            </item>
            <separator/>
            <item label="Terminal">
                <action name="Execute">
                    <command>xterm</command>
                </action>
            </item>
            <separator/>
            <item label="Exit">
                <action name="Exit"/>
            </item>
        </menu>
    </openbox_menu>
  '';

  xdg.configFile."openbox/autostart".text = # bash
    ''
      picom -b --fade-in-step=0.1 --fade-out-step=0.2
      tint2 &
    '';

  home.file.".xinitrc".text = # bash
    ''
      #!/bin/sh

      exec openbox-session
    '';
}
