FROM toolbox:base

RUN nvim --headless -c "Lazy! sync" -c "qa!" \
	&& rm -rf ~/.cache

RUN nvim --headless \
	-u NORC \
	-c 'lua vim.opt.rtp:prepend(vim.fn.stdpath("data") .. "/lazy/lazy.nvim")' \
	-c 'lua require("plugins")' \
	-c "TSInstallSync all" \
	-c "qa!" \
	&& rm -rf ~/.cache
