---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  containers:
    - image: toolbox
      name: toolbox
      # ports:
      #   - containerPort: 8000
      #     hostPort: 8000
      #     protocol: TCP
      #   - containerPort: 6060
      #     hostPort: 6060
      #     protocol: TCP
      env:
        - name: TERM
          value: ${TERM}
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
      tty: true
      stdin: true
      workingDir: /workspaces
      volumeMounts:
        - name: toolbox-workspaces
          mountPath: /workspaces:Z
        - name: toolbox-cache
          mountPath: "${HOME}/.cache"
        - name: toolbox-cargo-data
          mountPath: "${HOME}/.cargo"
        - name: toolbox-local
          mountPath: "${HOME}/.local"
        - name: toolbox-go-data
          mountPath: "${HOME}/go"
        - name: tmp
          mountPath: /tmp
  restartPolicy: Never
  volumes:
    - name: toolbox-workspaces
      hostPath:
        path: "./workspaces"
        type: Directory

    - name: toolbox-cache
      persistentVolumeClaim:
        claimName: toolbox-cache

    - name: toolbox-cargo-data
      persistentVolumeClaim:
        claimName: toolbox-cargo-data

    - name: toolbox-local
      persistentVolumeClaim:
        claimName: toolbox-local

    - name: toolbox-go-data
      persistentVolumeClaim:
        claimName: toolbox-go-data

    - name: tmp
      emptyDir:
        medium: Memory
        sizeLimit: 1Gi
