---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  containers:
    - image: toolbox
      name: toolbox
      # ports:
      #   - containerPort: 8000
      #     hostPort: 8000
      #     protocol: TCP
      #   - containerPort: 6060
      #     hostPort: 6060
      #     protocol: TCP
      env:
        - name: TERM
          value: ${TERM}
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
      tty: true
      stdin: true
      workingDir: /workspaces
      volumeMounts:
        - name: toolbox-workspaces
          mountPath: /workspaces:Z

        - name: toolbox-cargo-data
          mountPath: "${HOME}/.cargo"

        - name: toolbox-go-data
          mountPath: "${HOME}/go"

        - name: toolbox-cache
          mountPath: "${HOME}/.cache"

        - name: toolbox-nvim-share
          mountPath: "${HOME}/.local/share/nvim"

        - name: toolbox-nvim-state
          mountPath: "${HOME}/.local/state/nvim"

        - name: tmp
          mountPath: /tmp

  restartPolicy: Never
  volumes:
    - name: toolbox-workspaces
      hostPath:
        path: "${HOME}/toolbox/workspaces"
        type: Directory

    - name: toolbox-cargo-data
      persistentVolumeClaim:
        claimName: toolbox-cargo-data

    - name: toolbox-go-data
      persistentVolumeClaim:
        claimName: toolbox-go-data

    - name: toolbox-cache
      emptyDir:
        medium: Memory

    - name: toolbox-nvim-share
      emptyDir:
        medium: Memory

    - name: toolbox-nvim-state
      emptyDir:
        medium: Memory

    - name: tmp
      emptyDir:
        medium: Memory
