---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: toolbox
  name: toolbox_pod
spec:
  containers:
    - image: toolbox
      name: toolbox
      # ports:
      #   - containerPort: 6060
      #     hostPort: 6060
      #     protocol: TCP
      env:
        - name: TERM
          value: ${TERM}
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        seLinuxOptions:
          type: spc_t
      tty: true
      stdin: true
      workingDir: /workspaces
      volumeMounts:
        - name: toolbox-workspaces
          mountPath: /workspaces
        - name: toolbox-cache
          mountPath: "${USER_HOME}/.cache"
        - name: toolbox-nvim-data
          mountPath: "${USER_HOME}/.local/share/nvim"
        - name: toolbox-direnv-data
          mountPath: "${USER_HOME}/.local/share/direnv"
        - name: toolbox-go-global
          mountPath: "${USER_HOME}/go"
        - name: toolbox-cargo-data
          mountPath: "${USER_HOME}/.cargo"
        - name: toolbox-local-bin
          mountPath: "${USER_HOME}/.local-bin"
        - name: toolbox-local-lib
          mountPath: "${USER_HOME}/.local-lib"
  restartPolicy: Never
  volumes:
    - name: toolbox-workspaces
      hostPath:
        path: "${WORKSPACE_HOST_PATH}"
        type: Directory

    - name: toolbox-cache
      persistentVolumeClaim:
        claimName: toolbox-cache

    - name: toolbox-nvim-data
      persistentVolumeClaim:
        claimName: toolbox-nvim-data

    - name: toolbox-direnv-data
      persistentVolumeClaim:
        claimName: toolbox-direnv-data

    - name: toolbox-go-global
      persistentVolumeClaim:
        claimName: toolbox-go-global

    - name: toolbox-cargo-data
      persistentVolumeClaim:
        claimName: toolbox-cargo-data

    - name: toolbox-local-bin
      persistentVolumeClaim:
        claimName: toolbox-local-bin

    - name: toolbox-local-lib
      persistentVolumeClaim:
        claimName: toolbox-local-lib
status: {}
