local function escape_backticks(s)
	local _, backtick_count = string.gsub(s, "`", "")
	local ticks = string.rep("`", backtick_count + 1)
	return string.format("%s %s %s", ticks, s, ticks)
end

local function generate_keymap()
	local table_gen = require("table_gen")
	local headings = { "mode", "lhs", "rhs", "desc" }
	local keys = {}
	for _, m in pairs(vim.api.nvim_get_keymap("")) do
		if m.lhs:find("<Plug>", 1, true) ~= 1 then
			table.insert(keys, m)
		end
	end

	table.sort(keys, function(a, b)
		if a.mode < b.mode then
			return true
		elseif a.mode > b.mode then
			return false
		end

		return a.lhs < b.lhs
	end)

	local rows = {}

	for _, m in ipairs(keys) do
		table.insert(rows, {
			string.format("`%s`", m.mode),
			string.format("`%s`", m.lhs),
			m.rhs and escape_backticks(m.rhs) or "",
			m.desc,
		})
	end

	return table_gen(rows, headings, {
		style = "Markdown (Github)",
	})
end

local function generate_user_commands()
	local table_gen = require("table_gen")
	local headings = { "name", "definition" }
	local rows = {}

	local commands = {}
	for _, c in pairs(vim.api.nvim_get_commands({})) do
		table.insert(commands, c)
	end

	table.sort(commands, function(a, b)
		return a.name < b.name
	end)

	for _, c in ipairs(commands) do
		table.insert(rows, {
			string.format("`%s`", c.name),
			string.format("`%s`", c.definition),
		})
	end

	return table_gen(rows, headings, {
		style = "Markdown (Github)",
	})
end

vim.api.nvim_create_user_command("GenerateDocs", function()
	local file_path = vim.fn.stdpath("config") .. "/README.md"
	local log_file = assert(io.open(file_path, "w"))

	assert(io.output(log_file))

	assert(io.write("# Neovim documentation (generated by `GenerateDocs` command)\n\n"))

	assert(io.write("## Neovim keymap\n"))
	local keymap = generate_keymap()
	assert(io.write(keymap .. "\n\n"))

	assert(io.write("## Neovim commands\n"))
	local commands = generate_user_commands()
	assert(io.write(commands .. "\n\n"))

	assert(io.close(log_file))
end, {})
