vim.cmd "packadd pkg-nvim"
local pkg = require "pkg-nvim".pkg

pkg "b3nj5m1n/kommentary"
pkg "neovim/nvim-lspconfig"
pkg "nvim-treesitter/nvim-treesitter"
pkg "hrsh7th/nvim-compe"
pkg "ray-x/lsp_signature.nvim"
pkg "sheerun/vim-polyglot"
pkg "junegunn/fzf.vim"
pkg "airblade/vim-gitgutter"
pkg "sebdah/vim-delve"
pkg "Townk/vim-autoclose"
pkg "neomake/neomake"
pkg "tpope/vim-fugitive"
pkg "mhartington/formatter.nvim"
pkg "rbtnn/vim-vimscript_indentexpr"
pkg "svermeulen/vimpeccable"
pkg "norcalli/nvim-colorizer.lua"
pkg "gfanto/fzf-lsp.nvim"
pkg "nvim-lua/lsp_extensions.nvim"
pkg "rktjmp/lush.nvim"
