---
linters:
  enable-all: true
  disable:
    - wsl
    - testpackage
    - nlreturn
    - gomodguard
    - depguard
    - gochecknoinits
    - gochecknoglobals
    - exhaustivestruct
    - gomnd
    - forbidigo
    - errorlint
    - wrapcheck
    - goerr113
    - paralleltest
    - predeclared
