---
linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - varcheck
    - bidichk
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - exportloopref
    - gocritic
    - godot
    - gomnd
    - gomoddirectives
    - goprintffuncname
    - gosec
    - misspell
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - predeclared
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - wastedassign
linters-settings:
  govet:
    enable-all: true
