#!/usr/bin/env node

const { execSync } = require("child_process");
let path = require("path");

// Shift program and script.
process.argv.shift();
process.argv.shift();

// Make the file argument absolute.
for (let i = 0; i < process.argv.length; i++) {
  let arg = process.argv[i];
  if (arg.includes(".")) {
    process.argv[i] = path.join(process.cwd(), arg);
  }
}

// Call eslint through current project npx.
let stdout = execSync("npx --offline eslint " + process.argv.join(" "));

console.log(stdout.toString());
