#!/bin/env bash

set -eo pipefail

# Called by Neomake.

if npm list --depth=0 eslint &>/dev/null; then
	# Use eslint from project dir if available.
	npx --offline eslint "$@"
else
	# Otherwise use global eslint.
	/usr/bin/eslint "$@"
fi
