#!/usr/bin/env bash

set -euo pipefail

repo="$(gh repo view --json nameWithOwner --template '{{.nameWithOwner}}')"

export GH_REPO="$repo"
export FZF_DEFAULT_COMMAND="gh-search prs {q}"

fzf --bind "change:reload:sleep 0.1; $FZF_DEFAULT_COMMAND || true" --ansi --phony --query '' \
	--preview "gh-pr-view {1} | rg --colors=match:bg:yellow --color=always --passthru {q}" \
	--preview-window=wrap \
	--prompt "Pull requests> "
