#!/usr/bin/env bash

set -eo pipefail

target="$1"

if [ "$target" != "prs" ] && [ "$target" != "issues" ] && [ "$target" != "events" ]; then
	echo "usage: gh-fzf {prs|issues|events}"
	exit 1
fi

set -e

export target

tmpdir="/tmp/gh-tpl.$$"
mkdir -p "$tmpdir"
export tmpdir

function cleanup {
	rm -rf "$tmpdir"
}

trap cleanup EXIT

# Note: skipping pullRequest.comments, these are included in timeline.
pr_query="$(
	cat <<-'EOF'
		query($name: String!, $owner: String!, $number: Int!) {
			repository(owner: $owner, name: $name) {
				pullRequest(number: $number) {
					number,
					title,
					url,
					updatedAt,
					createdAt,
					state,
					author {
						login
					},
					body,
					reviews(last: 100) {
						nodes {
							updatedAt,
							createdAt,
							url,
							state,
							author {
								login
							},
							minimizedReason,
							body,
							comments(last: 100) {
								nodes {
									updatedAt,
									createdAt,
									url,
									author {
										login
									},
									minimizedReason,
									position,
									startLine,
									line,
									originalStartLine,
									originalLine,
									diffHunk,
									body
								}
							}
						}
					}
				}
			}
		}
	EOF
)"

export pr_query

pr_jq_template="$(
	cat <<-'EOF'
		.data.repository.pullRequest | .comments = ([
			# Reviews.
			(.reviews.nodes[] | select(.body != "") | .html_url = .url), # Skip placeholder reviews.

			# Review comments.
			(.reviews.nodes[] | . as $review | .comments.nodes[] | . as $comment | .state = $review.state | .diffHunk = ([
				(.diffHunk | split("\n") | . as $arr | to_entries[] |
				# Note: line numbers are for files not diff, can't use them here unless we see all hunks.
				if $comment.originalStartLine == null and $comment.originalLine != null then
					select(.key > ($arr|length)-5)
				else
					select(true)
				end
				| .value)
			] | join("\n")) | .html_url = .url)
		] | sort_by(.createdAt))
	EOF
)"

export pr_jq_template

issue_query="$(
	cat <<-'EOF'
		query($name: String!, $owner: String!, $number: Int!) {
			repository(owner: $owner, name: $name) {
				issue(number: $number) {
					number,
					title,
					url,
					updatedAt,
					createdAt,
					state,
					author {
						login
					},
					body,
					comments(last: 100) {
						nodes {
							updatedAt,
							createdAt,
							url,
							author {
								login
							},
							minimizedReason,
							body
						}
					}
				}
			}
		}
	EOF
)"

export issue_query

issue_jq_template="$(
	cat <<-'EOF'
		.data.repository.issue | .comments = .comments.nodes
	EOF
)"

export issue_jq_template

issue_timeline_jq_template="$(
	cat <<-'EOF'
		[
			.[] | .createdAt = (
				if has("created_at") then
					.created_at
				elif has("submitted_at") then
					.submitted_at
				elif has("committer") then
					.committer.date
				end
			) | .author.login = (
				if has("author") then
					.author.name
				elif has("actor") then
					.actor.login
				elif has("user") then
					.user.login
				end
			) | .url = (
				if has("html_url") then
					.html_url
				else
					null
				end
			) | select(.event != "subscribed" and .event != "unsubscribed" and .event != "mentioned")
		]
	EOF
)"

export issue_timeline_jq_template

issue_pr_header_go_template="$(
	cat <<-'EOF'
		# #{{.number}} {{.title}} {{(printf "(%s)" .state) | autocolor "red"}}
		## *{{timeago .createdAt}}{{if and .updatedAt (gt .updatedAt .createdAt)}}{{printf " (updated %s)" (timeago .updatedAt) }}{{end}}{{if .author}}{{printf " (%s)" .author.login}}{{end}}:*
		{{.url}}

		{{.body}}
	EOF
)"

export issue_pr_header_go_template

issue_pr_comments_go_template="$(
	cat <<-'EOF'
		{{range .}}
			---

			## *{{timeago .createdAt}}{{if and .updatedAt (gt .updatedAt .createdAt)}}{{printf " (updated %s)" (timeago .updatedAt) }}{{end}}{{if .author}} {{printf "(%s)" .author.login}}{{end}}{{if .state}} {{.state | lower | autocolor "red"}}{{end}}{{if .event}} {{.event | lower | autocolor "red"}}{{end}}:*
			{{if .html_url}}{{.html_url}}{{end}}

			{{if .minimizedReason}}***minimized: {{.minimizedReason}}***{{end}}
			{{if .path}}***path: {{.path}}***{{end}}
			{{if .diffHunk}}{{printf "```diff\n%s\n```" .diffHunk}}{{end}}
			{{if .body}}{{.body}}{{end}}
			{{if .sha}}{{.sha | trunc 7 | autocolor "yellow"}}{{- printf " %s" .message}}{{end}}
			{{if .assignee}}***{{.assignee.login}}***{{end}}
			{{if .label}}***{{.label.name}}***{{end}}
			{{if .rename}}***{{printf "~~%s~~ %s" .rename.from .rename.to}}***{{end}}
			{{if .source.issue}}
				***{{printf "#%v" .source.issue.number}} {{.source.issue.title}}***

				{{.source.issue.html_url}}
			{{end}}
			{{if .source.pull_request}}
				***{{printf "#%v" .source.pull_request_number}} {{.source.pull_request.title}}***

				{{.source.pull_request.html_url}}
			{{end}}
			{{if .project_id}}***project: {{.project_id}}***{{end}}
			{{if .column}}***{{.column}}***{{end}}
			{{if .project_card.previous_column_name}}
				***{{printf "%s -> %s" .project_card.previous_column_name .project_card.column_name}}***
			{{else if .project_card.column_name}}
				***{{.project_card.column_name}}***
			{{end}}
			{{if .lock_reason}}***{{.lock_reason}}***{{end}}
			{{if .state_reason}}***{{.state_reason}}***{{end}}
			{{if .milestone}}***{{.milestone.title}}***{{end}}
			{{if .dismissed_review}}{{.dismissed_review.dismissal_message}}{{end}}
			{{if .requested_reviewer}}***{{.requested_reviewer.login}}***{{end}}
			{{if .requested_team}}***{{.requested_team.name}}***{{end}}
		{{end}}
	EOF
)"

export issue_pr_comments_go_template

issue_pr_list_go_template="$(
	cat <<-'EOF'
		{{- range .}}{{.number | autocolor "yellow"}} {{timeago .createdAt | autocolor "red"}} {{printf "(%s)" .author.login | autocolor "blue"}} {{regexReplaceAllLiteral "[\r\n]+" .title " "}} {{(printf "(%s)" .state) | autocolor "red"}}{{"\n"}}{{end -}}
	EOF
)"

export issue_pr_list_go_template

function render-markdown {
	set -euo pipefail

	glow --style auto --width "$FZF_PREVIEW_COLUMNS"

	# Other options.
	# mdcat --ansi --columns "$FZF_PREVIEW_COLUMNS"
	# rich --markdown --force-terminal --emoji -
	#
	# HTML options.
	# cmark-gfm --to html --width "$FZF_PREVIEW_COLUMNS" | elinks -dump -dump-color-mode 3
	# marked --gfm | elinks -dump -dump-color-mode 3
}

export -f render-markdown

function gh-search {
	set -euo pipefail

	repo="$1"
	id="$2"

	if [ "$target" == "prs" ] || [ "$target" == "issues" ]; then
		# Handle empty query.
		if [ "$id" == "{q}" ] || [ "$id" == "" ]; then
			gh "${target::-1}" list \
				--state=all \
				--json number,title,state,createdAt,updatedAt,author \
				--jq 'sort_by(.updatedAt) | reverse' |
				gh-tpl --color "$issue_pr_list_go_template"
			exit
		fi

		gh search "$target" \
			--repo "$repo" \
			--sort updated \
			--json number,title,state,createdAt,author \
			"$id" |
			gh-tpl --color "$issue_pr_list_go_template"
	fi
}

export -f gh-search

function gh-view {
	set -euo pipefail

	number="$1"

	if [ "$number" == "" ]; then
		echo "usage: gh-view {number}"
		exit 1
	fi

	timeline_path="$tmpdir/timeline"
	issue_pr_path="$tmpdir/issue"

	gh api \
		-H "Accept: application/vnd.github+json" \
		-H "X-GitHub-Api-Version: 2022-11-28" \
		"/repos/{owner}/{repo}/issues/$number/timeline" |
		gojq "$issue_timeline_jq_template" >"$timeline_path" &

	if [ "$target" == "prs" ]; then
		gh api graphql \
			-F owner='{owner}' \
			-F name='{repo}' \
			-F number="$number" \
			-f query="$pr_query" \
			--jq "$pr_jq_template" >"$issue_pr_path" &

		wait

		gh-tpl "$issue_pr_header_go_template" <"$issue_pr_path" |
			render-markdown

		comments="$(gojq '[ .comments[] ]' <"$issue_pr_path")"

		cat <(echo "$comments") "$timeline_path" |
			gojq -s 'add | sort_by(.createdAt)' |
			gh-tpl "$issue_pr_comments_go_template" |
			render-markdown
	elif [ "$target" == "issues" ]; then
		gh api graphql \
			-F owner='{owner}' \
			-F name='{repo}' \
			-F number="$number" \
			-f query="$issue_query" \
			--jq "$issue_jq_template" >"$issue_pr_path" &

		wait

		gh-tpl "$issue_pr_header_go_template" <"$issue_pr_path" |
			render-markdown

		gojq -s 'add | sort_by(.createdAt)' <"$timeline_path" |
			gh-tpl "$issue_pr_comments_go_template" |
			render-markdown
	fi
}

export -f gh-view

# PRs and issues use github's search.
if [ "$target" == "prs" ] || [ "$target" == "issues" ]; then
	repo="$(gh repo view --json nameWithOwner --jq '.nameWithOwner')"
	export FZF_DEFAULT_COMMAND="bash -c \"gh-search $repo {q} 2>&1\""

	fzf \
		--ansi \
		--phony \
		--query '' \
		--no-sort \
		--bind "change:reload:sleep 0.2; $FZF_DEFAULT_COMMAND || true" \
		--bind ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down \
		--bind shift-up:preview-top,shift-down:preview-bottom \
		--header "Ctrl-L: web browser, Ctrl-O: diff" \
		--bind "ctrl-l:execute-silent(gh ${target::-1} view {1} --web)" \
		--bind "ctrl-o:execute(gh pr diff {1} | delta)" \
		--preview 'bash -c "gh-view {1}" | rg -i --colors=match:fg:black --colors=match:bg:yellow --color=always --passthru {q}' \
		--prompt "$target> "

	exit
fi

event_list_go_template="$(
	cat <<-'EOF'
		{{- range . -}}
			{{" "}}{{.id | autocolor "yellow" -}}
			{{" "}}{{- timeago .created_at | autocolor "red"}} {{printf "(%s@%s)" .actor.login .repo.name | autocolor "blue" -}}
			{{- if .payload.pull_request}} {{printf "(#%v) %s" .payload.pull_request.number .payload.pull_request.title | autocolor "cyan"}}{{end -}}
			{{- if .payload.issue}} {{printf "(#%v) %s" .payload.issue.number .payload.issue.title | autocolor "cyan"}}{{end -}}
			{{- if .payload.ref}}
				{{- if (or (hasSuffix "main" .payload.ref) (hasSuffix "master" .payload.ref))}}
					{{- (printf " (%s)" .payload.ref) | autocolor "red" -}}
				{{else}}
					{{- (printf " (%s)" .payload.ref) | autocolor "cyan" -}}
				{{end -}}
			{{end -}}
			{{- printf " %s" (trimSuffix "Event" .type) | autocolor "yellow" -}}
			{{- if .payload.ref_type}} {{.payload.ref_type}}{{end -}}
			{{- if .payload.action}} {{(printf "(%s)" .payload.action) | autocolor "red"}}{{end -}}
			{{- if .payload.review.state}} {{(printf "(%s)" .payload.review.state) | autocolor "red"}}{{end -}}

			{{- if .payload.review.commit_id}} {{.payload.review.commit_id | trunc 7 | autocolor "yellow"}}{{end -}}
			{{- if .payload.review.body}} {{(regexReplaceAllLiteral "[\r\n]+" .payload.review.body " ")}}{{end -}}
			{{- if .payload.comment.body}} {{(regexReplaceAllLiteral "[\r\n]+" .payload.comment.body " ")}}{{end -}}
			{{- if .payload.commits}}
				{{- (printf " (%v %s)" .payload.size (int .payload.size | plural "commit" "commits")) | autocolor "red" -}}
				{{- range .payload.commits -}}
					{{- printf " %s" (regexReplaceAllLiteral "[\r\n]+" .message " ") -}}
				{{- end -}}
			{{end -}}
			{{- "\n" -}}
		{{- end -}}
	EOF
)"

event_view_go_template="$(
	cat <<-'EOF'
		{{if .payload.review.body}} {{.payload.review.body}}{{end}}
		{{if .payload.comment.body}} {{.payload.comment.body}}{{end}}
		{{if .payload.commits}}
			{{range .payload.commits}}
				* {{.sha | trunc 7 | autocolor "yellow"}} {{.message}}
			{{end}}
		{{end}}
	EOF
)"

export event_view_go_template

function view-event {
	id="$(echo "$1" | tr -d "'")"

	gojq ".[] | select(.id == \"$id\")" |
		gh-tpl "$event_view_go_template" |
		render-markdown
}

export -f view-event

# Events uses fzf filtering.
if [ "$target" == "events" ]; then
	user=$(gh api user --jq '.login')

	events_path="$tmpdir/events"
	received_events_path="$tmpdir/received_events"

	# List events for the authenticated user.
	gh api \
		-H "Accept: application/vnd.github+json" \
		-H "X-GitHub-Api-Version: 2022-11-28" \
		"/users/$user/events" >"$events_path" &

	# List events received by the authenticated user.
	gh api \
		-H "Accept: application/vnd.github+json" \
		-H "X-GitHub-Api-Version: 2022-11-28" \
		"/users/$user/received_events" >"$received_events_path" &

	wait

	cat "$events_path" "$received_events_path" |
		gojq -s 'add | sort_by(.created_at) | reverse' |
		gh-tpl --color "$event_list_go_template" |
		fzf \
			--ansi \
			--no-sort \
			--exact \
			-i \
			--bind ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down \
			--bind shift-up:preview-top,shift-down:preview-bottom \
			--preview "bash -c \"cat \"$events_path\" \"$received_events_path\" | view-event {1} | rg -i --colors=match:fg:black --colors=match:bg:yellow --color=always --passthru {q}\"" \
			--preview-window=down \
			--prompt "$target> "

	exit
fi
