#!/usr/bin/env bash

set -euo pipefail

number="$1"

# Issue with comments.
pr=$(gh issue view "$number" --json number,title,state,createdAt,author,body,comments \
	--jq '. as $parent | {createdAt, number, title, state, login: .author.login, comments: [({createdAt: $parent.createdAt, login: $parent.author.login, body: $parent.body}), ($parent.comments[] | {createdAt, login: .author.login, body})]}')

# Display the issue using gh-tpl: https://github.com/mgnsk/gh-tpl.
echo "$pr" | gh-tpl '# #{{.number}} {{.title}}{{"\n"}}state: {{.state}}{{"\n\n\n"}}{{range .comments}}{{"\n\n\n"}}# *{{timeago .createdAt}} {{printf "(%s)" .login}}:*{{"\n"}}{{if .diff_hunk}}{{printf "```diff\n%s\n```" .diff_hunk}}{{end}}{{"\n"}}{{.body}}{{end}}' | glow -s auto
