#!/usr/bin/env bash

set -euo pipefail

target="$1"
query="$2"

if [ "$target" != "prs" ] && [ "$target" != "issues" ]; then
	echo "usage: gh-search {prs|issues} {q}"
	exit 1
fi

source "$(dirname "$0")/gh-lib/templates.sh"

# Handle empty query.
if [ "$query" == "{q}" ] || [ "$query" == "" ]; then
	gh "${target::-1}" list --json number,title,state,createdAt,author | gh-tpl --color "$issue_pr_list_go_template"
	exit
fi

if [ "$target" == "prs" ] || [ "$target" == "issues" ]; then
	gh search "$target" --repo "$(printenv GH_REPO)" --sort updated --json number,title,state,createdAt,author "$query" | gh-tpl --color "$issue_pr_list_go_template"
fi
