#!/usr/bin/env bash

set -euo pipefail

target="$1"
query="$2"
list_template='{{range .}}{{.number | autocolor "yellow"}} {{timeago .createdAt | autocolor "red"}} {{printf "(%s)" .author.login | autocolor "blue"}} {{.title | replace "\n" " "}} ({{.state}}){{"\n"}}{{end}}'

if [ "$target" != "prs" ] && [ "$target" != "issues" ]; then
	echo "usage: gh-search {prs|issues} {q}"
	exit 1
fi

# Handle empty query.
if [ "$query" == "{q}" ] || [ "$query" == "" ]; then
	gh "${target::-1}" list --json number,title,state,createdAt,author | gh-tpl --color "$list_template"
	exit
fi

gh search "$target" --repo "$(printenv GH_REPO)" --sort updated --json number,title,state,createdAt,author "$query" | gh-tpl --color "$list_template"
