#!/usr/bin/env bash

# Requires gh-tpl: https://github.com/mgnsk/gh-tpl.

set -euo pipefail

target="$1"
number="$2"
issue_pr_jq_template='. as $parent | {url, createdAt, number, title, state, login: .author.login, comments: [({url, createdAt: $parent.createdAt, login: $parent.author.login, body: $parent.body}), ($parent.comments[] | {url, createdAt, login: .author.login, body})]}'
issue_pr_go_template='# #{{.number}} {{.title}}{{"\n"}}state: {{.state}}{{"\n\n\n"}}{{range .comments}}{{"\n\n\n"}}# *{{timeago .createdAt}} {{printf "(%s)" .login}}:*{{"\n"}}{{.url}}{{"\n"}}{{if .diff_hunk}}{{printf "```diff\n%s\n```" .diff_hunk}}{{end}}{{"\n"}}{{.body}}{{end}}'

if [ "$target" == "pr" ]; then
	# PR with body and comments. The PR body is treated as the first comment.
	pr=$(gh pr view "$number" --json number,url,title,state,createdAt,author,body,comments --jq "$issue_pr_jq_template")

	# Diff comments.
	diff_comments=$(gh api "repos/{owner}/{repo}/pulls/$number/comments" | jq ' [.[] | {url, createdAt: .created_at, login: .user.login, diff_hunk, body}]')

	# PR with all comments merged and sorted.
	pr_joined=$(jq -n -s --argjson pr "$pr" --argjson diff_comments "$diff_comments" '{url: $pr.url, createdAt: $pr.createdAt, number: $pr.number, title: $pr.title, state: $pr.state, login: $pr.login, comments: ($pr.comments + $diff_comments) | sort_by(.createdAt)}')

	echo "$pr_joined" | gh-tpl "$issue_pr_go_template" | glow -s auto

	# Show the full diff.
	gh pr diff "$number" | delta
elif [ "$target" == "issue" ]; then
	gh issue view "$number" --json number,url,title,state,createdAt,author,body,comments --jq "$issue_pr_jq_template" | gh-tpl "$issue_pr_go_template" | glow -s auto
else
	echo "usage: gh-view {pr|issue} {number}"
	exit 1
fi
