#!/usr/bin/env bash

set -euo pipefail

target="$1"
number="$2"

if [ "$number" == "" ]; then
	echo "number argument empty"
	exit 1
fi

pr_query="$(
	cat <<-'EOF'
		query($name: String!, $owner: String!, $number: Int!) {
			repository(owner: $owner, name: $name) {
				pullRequest(number: $number) {
					number,
					title,
					url,
					createdAt,
					state,
					author {
						login
					},
					body,
					comments(last: 100) {
						nodes {
							createdAt,
							url,
							author {
								login
							},
							minimizedReason,
							body
						}
					},
					reviews(last: 100) {
						nodes {
							createdAt,
							url,
							state,
							author {
								login
							},
							minimizedReason,
							body,
							comments(last: 100) {
								nodes {
									createdAt,
									url,
									author {
										login
									},
									minimizedReason,
									position,
									startLine,
									line,
									originalStartLine,
									originalLine,
									diffHunk,
									body
								}
							}
						}
					}
				}
			}
		}
	EOF
)"

pr_jq_template="$(
	cat <<-'EOF'
		.data.repository.pullRequest | .comments = ([
			# Comments.
			(.comments.nodes[]),

			# Reviews.
			(.reviews.nodes[] | select(.body != "")), # Skip placeholder reviews.

			# Review comments.
			(.reviews.nodes[] | . as $review | .comments.nodes[] | . as $comment | .state = $review.state | .diffHunk = ([
				(.diffHunk | split("\n") | . as $arr | to_entries[] |
				# Note: line numbers are for files not diff, can't use them here unless we see all hunks.
				if $comment.originalStartLine == null and $comment.originalLine != null then
					select(.key > ($arr|length)-5)
				else
					select(true)
				end
				| .value)
			] | join("\n")))
		] | sort_by(.createdAt))
	EOF
)"

issue_query="$(
	cat <<-'EOF'
		query($name: String!, $owner: String!, $number: Int!) {
			repository(owner: $owner, name: $name) {
				issue(number: $number) {
					number,
					title,
					url,
					createdAt,
					state,
					author {
						login
					},
					body,
					comments(last: 100) {
						nodes {
							createdAt,
							url,
							author {
								login
							},
							minimizedReason,
							body
						}
					}
				}
			}
		}
	EOF
)"

issue_jq_template="$(
	cat <<-'EOF'
		.data.repository.issue | .comments = .comments.nodes
	EOF
)"

issue_pr_go_template="$(
	cat <<-'EOF'
		# #{{.number}} {{.title}} ({{.state}})
		## *{{timeago .createdAt}}{{if .author}} {{printf "(%s)" .author.login}}{{end}}:*
		*{{.url}}*

		{{.body}}

		{{range .comments}}
			---

			## *{{timeago .createdAt}}{{if .author}} {{printf "(%s)" .author.login}}{{end}}{{if .state}} {{.state}}{{end}}:*
			*{{.url}}*
			{{if .minimizedReason}}*minimized: {{.minimizedReason}}*{{end}}
			{{if .path}}*path: {{.path}}*{{end}}
			{{if .diffHunk}}{{printf "```diff\n%s\n```" .diffHunk}}{{end}}
			{{.body}}
		{{end}}
	EOF
)"

function render {
	# mdcat: Best readability. Respects user colors.
	mdcat -p --ansi --columns "$FZF_PREVIEW_COLUMNS"

	# rich-cli: Less readable. Respects user colors.
	# rich --markdown --force-terminal --emoji -

	# HTML options.
	# cmark-gfm --to html --width "$FZF_PREVIEW_COLUMNS" | elinks -dump -dump-color-mode 3
	# marked --gfm | elinks -dump -dump-color-mode 3

	# glow: Poor performance. Italic URLs don't display.
	# glow --pager --style auto --width "$FZF_PREVIEW_COLUMNS"
}

if [ "$target" == "pr" ]; then
	gh api graphql -F owner='{owner}' -F name='{repo}' -F number="$number" -f query="$pr_query" --jq "$pr_jq_template" | gh-tpl "$issue_pr_go_template" | render
	# gh pr diff "$number" | delta
elif [ "$target" == "issue" ]; then
	gh api graphql -F owner='{owner}' -F name='{repo}' -F number="$number" -f query="$issue_query" --jq "$issue_jq_template" | gh-tpl "$issue_pr_go_template" | render
else
	echo "usage: gh-view {pr|issue} {number}"
	exit 1
fi
