#!/bin/env bash

set -e

prog="$1"

if [[ "$prog" == "" ]]; then
	echo "Usage: ide {program} [args]"
	exit 1
fi

args=(
	--unshare-all
	--share-net
	--die-with-parent
	--setenv USERHOST_COLOR '\[\e[0;33m\]'
	--dev /dev
	--proc /proc
	--cap-drop ALL
)

declare -A ro_binds=(
	["/bin"]="/bin"
	["/usr"]="/usr"
	["/lib"]="/lib"
	["/lib64"]="/lib64"
	["/etc"]="/etc"
	["$HOME/.npm-packages"]="$HOME/.npm-packages"
	["$HOME/.go-packages"]="$HOME/.go-packages"
	["$HOME/.rustup"]="$HOME/.rustup"
)

# Mount all files tracked by dotfiles git.
for f in $(git -C "$HOME" ls-tree -r master --name-only); do
	ro_binds["$HOME/$f"]="$HOME/$f"
done

# Create per-project persistent volumes.
volumes=(
	".local"
	".cache"
)

repo=$(git rev-parse --show-toplevel)

# Fall back to PWD if no repo found.
if [[ "$repo" == "$HOME" ]]; then
	repo="$PWD"
fi

declare -A rw_binds=(
	["$PWD"]="$PWD"
	["$HOME/go"]="$HOME/go"
	["$HOME/.cargo"]="$HOME/.cargo"
)

for v in "${volumes[@]}"; do
	host_path="$HOME/.ide/$repo/$v"
	container_path="$HOME/$v"
	mkdir -p "$host_path"
	rw_binds["$host_path"]="$container_path"
done

tmpfs_volumes=(
	"/tmp"
	"/run/user/$(id -u)"
)

for key in "${!ro_binds[@]}"; do
	args+=(
		--ro-bind "$key" "${ro_binds[$key]}"
	)
done

for key in "${!rw_binds[@]}"; do
	args+=(
		--bind "$key" "${rw_binds[$key]}"
	)
done

for v in "${tmpfs_volumes[@]}"; do
	args+=(
		--tmpfs "$v"
	)
done

args+=(
	"$(which "$prog")"
	--
	"${@:2}"
)

bwrap "${args[@]}"
