#!/bin/env bash

set -e

prog="$1"

if [[ "$prog" == "" ]]; then
	echo "Usage: ide {program} [args]"
	exit 1
fi

args=(
	--dev-bind /dev /dev
	--proc /proc
	--tmpfs /tmp
	--tmpfs "/run/user/$(id -u)"
	--tmpfs "$HOME/.cache"
	--tmpfs "$HOME/.local/share"
	--tmpfs "$HOME/.local/state"
	--ro-bind /bin /bin
	--ro-bind /usr /usr
	--ro-bind /lib /lib
	--ro-bind /lib64 /lib64
	--ro-bind /etc /etc
	--setenv USERHOST_COLOR '\[\e[0;33m\]'
	--unshare-all
	--share-net
	--new-session
	--die-with-parent
	--bind "$PWD" "$PWD"
	--bind "$HOME/go" "$HOME/go"
	--bind "$HOME/.cargo" "$HOME/.cargo"
)

# Bind mount all files tracked by dotfiles git.
for f in $(git -C "$HOME" ls-tree -r master --name-only); do
	args+=(
		--bind "$HOME/$f" "$HOME/$f"
	)
done

args+=(
	"$(which "$prog")"
	--
	"${@:2}"
)

bwrap "${args[@]}"
