#!/bin/env bash

set -euo pipefail

PS3='Please enter your choice: '
options=("dev" "audio")
select opt in "${options[@]}"; do
	case $opt in
	"dev")
		break
		;;
	"audio")
		break
		;;
	*)
		echo "invalid option $REPLY"
		exit 1
		;;
	esac
done

nix develop "${HOME}?submodules=1#${opt}" --show-trace
