#!/bin/env bash

set -euo pipefail

TZ=$(timedatectl show --property=Timezone --value)
export TZ

mkdir -p \
	"${HOME}/go" \
	"${HOME}/.cargo"

docker compose -f "${HOME}/docker-compose.yml" -p ide run --rm ide
