#!/bin/env bash

set -euo pipefail

# Sort by PID descending.
pids=$(ps x --no-headers --format=pid,command --sort=-pid)

# Exclude PID of this script.
self="$$"

# NR>1 - exclude ps itself.
for pid in $(echo "$pids" | awk -v self="$self" 'NR>1 && !($1 == self)' | fzf --ignore-case --no-sort --exact --multi --accept-nth=1); do
	kill -9 "$pid"
done
