#!/bin/env bash

set -euo pipefail

# Lock the screen.
swaylock -f -c 000000

# Lock the session.
loginctl lock-session

# Lock 1password manually if it is running (it does not respect DBUS locking).
if command -v 1password &>/dev/null; then
	if pidof 1password; then
		1password --lock
	fi
fi
