#!/bin/env bash

set -e

if [ -e /home/deck/.nix-profile/etc/profile.d/nix.sh ]; then . /home/deck/.nix-profile/etc/profile.d/nix.sh; fi

# https://github.com/nix-community/nix-user-chroot
nix-user-chroot ~/.nix bash
